apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ecr-cleanup
  name: ecr-cleanup
rules:
  - apiGroups: ["v1"]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps/v1"]
    resources: ["daemonsets ", "deployments", "statefulsets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["batch/v1"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ecr-cleanup
  name: ecr-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-cleanup
subjects:
  - namespace: ecr-cleanup
    kind: ServiceAccount
    name: ecr-cleanup
